# Data Processing (Selection, Multi-indexing, and Pivot)


* The Airline On-Time Performance Data is adopted from [Tom Augspurger's](https://tomaugspurger.github.io/) [Modern Pandas](https://tomaugspurger.github.io/modern-1-intro) series.
* Adapted from the online pandas documentation. These slides are based on ones originally created by Prof. P. Louridas.

---

> J. Pavlopoulos, Assistant Professor <br />
> Department of Informatics <br />
> Athens University of Economics and Business (annis@aueb.gr)

## Pandas Axes

* In pandas, `DataFrames` exist on two axes.

* The row axis, going vertically, is axis 0.

* The column axis, going horizontally, is axis 1.

* So, when we do an operation on an entire row, we are going through axis 1.

* Similarly, when we do an operation on an entire column, we are going through axis 0.

# Using the `[]` operator

* The most obvious way to select stuff with pandas is with the `[]` operator.

* This provides familiarity with Python.

* However, it is usually not the optimal way.

* We do better by using more specialised methods.

## Selecting a Single Column

* We can select a single column by entering its name in `[]`.

* This yields a `Series` object.

* `df['A']` is equivalent to `df.A`.

* Setting the scene:

In [1]:
import pandas as pd
import numpy as np

dates = pd.date_range('20160101', periods=6)

dates

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')

In [2]:
df1 = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

df1

                   A         B         C         D
2016-01-01  1.024389  0.015717  1.617615  1.570675
2016-01-02  0.809808  0.279265  0.549680 -0.621381
2016-01-03  0.524435  0.086676 -1.427175  0.880090
2016-01-04 -1.347096  0.332749  0.026785 -0.845281
2016-01-05 -1.173197  1.575778  2.137439  0.333566
2016-01-06 -1.730565  1.489371  0.004361 -0.596810

In [3]:
df1['A']

2016-01-01    1.024389
2016-01-02    0.809808
2016-01-03    0.524435
2016-01-04   -1.347096
2016-01-05   -1.173197
2016-01-06   -1.730565
Freq: D, Name: A, dtype: float64

## Selecting Multiple Columns

* If we give a list of column names, we will get a dataframe with these columns.

In [4]:
df1[['A', 'C']]

                   A         C
2016-01-01  1.024389  1.617615
2016-01-02  0.809808  0.549680
2016-01-03  0.524435 -1.427175
2016-01-04 -1.347096  0.026785
2016-01-05 -1.173197  2.137439
2016-01-06 -1.730565  0.004361

## Selecting Rows

* If we pass a slice to `[]`, we will get a slice containing these rows.

* The right end is not included, as in standard Python.

In [5]:
df1[1:3]

                   A         B         C         D
2016-01-02  0.809808  0.279265  0.549680 -0.621381
2016-01-03  0.524435  0.086676 -1.427175  0.880090

## Columns with Numeric Names

* What will happen if our columns contain numeric names?

In [6]:
df2 = pd.DataFrame(np.random.randn(6,4), index=dates, columns=range(4))

df2

                   0         1         2         3
2016-01-01 -0.044957  1.309549  0.390279 -0.264343
2016-01-02  0.107051  1.580612  0.753370  0.486108
2016-01-03  0.082665  0.961390  0.774284  0.254590
2016-01-04 -0.342081  0.575258 -0.567025  0.913329
2016-01-05 -0.932139  0.124922 -0.230309  0.056603
2016-01-06 -3.277636  1.239157  1.153574 -1.092645

* When we pass a single number to `[]` we will select that column and will get the corresponding `Series`.

In [7]:
df2[2]

2016-01-01    0.390279
2016-01-02    0.753370
2016-01-03    0.774284
2016-01-04   -0.567025
2016-01-05   -0.230309
2016-01-06    1.153574
Freq: D, Name: 2, dtype: float64

* But if we pass a slice to `[]`, we will slice the rows.

In [8]:
df2[1:3]

                   0         1         2         3
2016-01-02  0.107051  1.580612  0.753370  0.486108
2016-01-03  0.082665  0.961390  0.774284  0.254590

* If we pass a list to `[]`, we will get the corresponding columns.

In [9]:
df2[[1, 2]]

                   1         2
2016-01-01  1.309549  0.390279
2016-01-02  1.580612  0.753370
2016-01-03  0.961390  0.774284
2016-01-04  0.575258 -0.567025
2016-01-05  0.124922 -0.230309
2016-01-06  1.239157  1.153574

* The situation remains the same if both our columns and our index are numeric.

In [10]:
df3 = pd.DataFrame(np.random.randn(6,4), columns=range(4))

df3

          0         1         2         3
0 -0.938339  1.828714  1.822001  0.206739
1 -0.046758 -0.746328 -0.337934  0.500709
2  0.243217  0.540857 -2.375821 -2.204040
3  1.066340  0.058821 -0.094804 -0.471732
4 -0.471856 -1.474281  1.094487  1.321901
5 -0.367685  1.311895  1.639750  0.326368

* Providing a slice to `[]` slices the *rows*, so that the right (i.e., the lower end; we are slicing vertically) end is *not* included.

In [11]:
df3[1:3]

          0         1         2         3
1 -0.046758 -0.746328 -0.337934  0.500709
2  0.243217  0.540857 -2.375821 -2.204040

* Note that all slice variations are supported, for example:

In [12]:
df3[1:6:2]

          0         1         2         3
1 -0.046758 -0.746328 -0.337934  0.500709
3  1.066340  0.058821 -0.094804 -0.471732
5 -0.367685  1.311895  1.639750  0.326368

* Providing a list to `[]` selects the *columns*.

In [13]:
df3[[1, 3]]

          1         3
0  1.828714  0.206739
1 -0.746328  0.500709
2  0.540857 -2.204040
3  0.058821 -0.471732
4 -1.474281  1.321901
5  1.311895  0.326368

* We can also use a boolean array to select the rows meeting the condition:

In [14]:
df1[df1['B'] > 0]

                   A         B         C         D
2016-01-01  1.024389  0.015717  1.617615  1.570675
2016-01-02  0.809808  0.279265  0.549680 -0.621381
2016-01-03  0.524435  0.086676 -1.427175  0.880090
2016-01-04 -1.347096  0.332749  0.026785 -0.845281
2016-01-05 -1.173197  1.575778  2.137439  0.333566
2016-01-06 -1.730565  1.489371  0.004361 -0.596810

#### Takeaways regarding `[]`

* With a DataFrame, slicing inside of `[]` *slices the rows*.

* With a DataFrame, passing a list (or an item) inside of `[]` *selects the columns*.

## Selection by *label* with `.loc`

* A *label* in pandas refers to the *index*.

* If the index is numeric, it may look like we are selecting based on the corresponding positions, *but it is not so*.

* There must be at least *one* row selected.

* In contrast to standard Python, both the *start* and *the end* are included in slices.

* Selection by label is performed with the `.loc` method.
* It accepts a:
    * **single label**, such as the number 5 or the label `'a'`. 
        * The number (e.g., 5) is interpreted as a label of the index (i.e., `'5'`). 
        * It is *not* a numeric position on the index. 
        * If the index is numeric, it just happens to look so.
    * **list or array** of labels, such as `['a', 'b', 'c']`.
    * **slice object** with labels `'a':'f'`.
        * Both ends are included!
        * Slice objects can be of the form `x:y:z`.
    * **boolean array**.
    * **callable** i.e., a function.

* Setting the scene:

In [15]:
import numpy as np
df1 = pd.DataFrame(np.random.randn(6,4),
                   index=list('abcdef'),
                   columns=list('ABCD'))

df1

          A         B         C         D
a  0.642311  0.185708  0.971465 -0.934730
b -1.047633 -0.427379 -0.280235  0.385009
c -0.256982 -0.632785 -0.894808 -1.803234
d  0.277395 -1.115639  0.429323  1.654368
e  1.147350 -1.063963  1.237968  1.319664
f  0.002466  2.078883 -0.616716 -1.215467

* Accessing the *row* via a single label:

In [16]:
df1.loc['a']

A    0.642311
B    0.185708
C    0.971465
D   -0.934730
Name: a, dtype: float64

* Note that a label is always a label, not a position, even if it happens to be numeric.

* To see that, let us create a frame with numeric indices:

In [17]:
df2 = pd.DataFrame(np.random.randn(6, 4),
                  index=range(5, -1, -1),
                  columns=list('ABCD'))
df2

          A         B         C         D
5  0.900140 -1.377499  1.659367  1.080876
4 -0.509129 -0.932476 -0.590295  0.762326
3  0.642075  0.642655 -0.437961 -1.296861
2 -0.832787 -1.029199 -0.527471  0.031114
1 -1.217562  0.268253 -1.184558  0.348173
0  0.612427  0.414169  1.168447  1.231341

In [18]:
df2.loc[1]

A   -1.217562
B    0.268253
C   -1.184558
D    0.348173
Name: 1, dtype: float64

* Back to `df1` for a list of labels:

In [19]:
df1.loc[['b', 'e']]

          A         B         C         D
b -1.047633 -0.427379 -0.280235  0.385009
e  1.147350 -1.063963  1.237968  1.319664

## Inclusion
* A slice where *both ends are included*:

In [20]:
df1.loc['b':'e']

          A         B         C         D
b -1.047633 -0.427379 -0.280235  0.385009
c -0.256982 -0.632785 -0.894808 -1.803234
d  0.277395 -1.115639  0.429323  1.654368
e  1.147350 -1.063963  1.237968  1.319664

* We can select both rows and columns. The columns are separated from the rows by `,`.

In [24]:
df1.loc['b':'e', # <== rows
        'B':'D'] # <== columns

          B         C         D
b -0.427379 -0.280235  0.385009
c -0.632785 -0.894808 -1.803234
d -1.115639  0.429323  1.654368
e -1.063963  1.237968  1.319664

## All rows but few columns
* If we want a projection on columns, containing all the rows, we use `:` for the rows:

In [25]:
df1.loc[:, 'B':'D']

          B         C         D
a  0.185708  0.971465 -0.934730
b -0.427379 -0.280235  0.385009
c -0.632785 -0.894808 -1.803234
d -1.115639  0.429323  1.654368
e -1.063963  1.237968  1.319664
f  2.078883 -0.616716 -1.215467

* Slicing treats the rows and the columns in their existing order in the data source.

* It **does not re-order them** in any way.

* Let's create a `DataFrame` with some sorted data to see what this means.

In [122]:
import pandas as pd
updown = pd.DataFrame({
    'A': range(1, 6),
    'X': range(11, 16),
    'B': range(6, 1, -1)},
    index=list('abxde'))
updown

   A   X  B
a  1  11  6
b  2  12  5
x  3  13  4
d  4  14  3
e  5  15  2

In [126]:
updown.sort_values(by='B', inplace=True)
updown

   A   X  B
e  5  15  2
d  4  14  3
x  3  13  4
b  2  12  5
a  1  11  6

* Now, if we take the slice from `b` to `d`, we'll just get an empty `DataFrame`:

In [127]:
updown.loc['b':'d']

Empty DataFrame
Columns: [A, X, B]
Index: []

* The slice from `d` to `b` will return the rows that appear in that interval.

* These *include* the `x` row.

In [128]:
updown.loc['d':'b']

   A   X  B
d  4  14  3
x  3  13  4
b  2  12  5

* Similarly, a slice from the `A` column to the `B` column will include the `X` column:

In [130]:
updown.loc['d':'b', 'A':'B']

   A   X  B
d  4  14  3
x  3  13  4
b  2  12  5

## Q: Can you decode what the following does?
```
df1.loc[:, df1.loc['a'] > 0]
```
* Will it return a row or a column?
* What will it comprise?

In [136]:
df1 # Show all rows & keep only columns w/positive value at index `a`.

          A         B         C         D
a  0.699162  0.277478  0.096886  0.999602
b -0.904538  2.019420 -0.330263  0.277574
c  0.137812  0.722670  1.362307  2.177825
d -0.202064 -1.291158 -1.328868  0.357604
e  1.478883  1.569192  0.071301 -0.421109
f  1.304271 -1.651930  0.286701  2.126461

In [31]:
df1.loc[:, df1.loc['a'] > 0]

          A         B         C
a  0.642311  0.185708  0.971465
b -1.047633 -0.427379 -0.280235
c -0.256982 -0.632785 -0.894808
d  0.277395 -1.115639  0.429323
e  1.147350 -1.063963  1.237968
f  0.002466  2.078883 -0.616716

## Selection by position: `.iloc`

* Selection by position means pure integer-based addressing.

* Positions start from 0 and their end is not included, as in standard Python (from 0 to length-1 of the axis).

* Selection by position in pandas is with the `.iloc` method.


* It accepts the following:
    * An integer, e.g., 5.
    * A list or array of integers, such as `[4, 3, 0]`.
    * A slice object with ints, like `1:7`.
    * Slice objects can be of the form `x:y:z`.
    * A boolean array.
    * A callable.

* Setting the scene.
* To make it obvious that a position is not the same as the label, we'll have integer labels, which in general will not coincide with the positions.

In [32]:
df1 = pd.DataFrame(np.random.randn(6,4),
                   index=list(range(0,12,2)),
                   columns=list(range(0,8,2)))
df1

           0         2         4         6
0  -0.867152 -0.767686  0.054296 -0.399826
2  -0.445409 -0.085144 -0.147879 -1.231636
4   0.451294  0.810422  0.846948  1.314204
6   1.499002  2.776847 -0.228980 -0.261825
8  -0.026715 -0.298624  0.206337 -0.383581
10  0.074069 -0.292211 -1.844412 -0.063091

* Accessing via an *integer* selects the **row** in that position:

In [33]:
df1.iloc[2]

0    0.451294
2    0.810422
4    0.846948
6    1.314204
Name: 4, dtype: float64

* Selecting with an *integer list* selects the **rows** in the respective positions:

In [34]:
df1.iloc[[1,3]]

          0         2         4         6
2 -0.445409 -0.085144 -0.147879 -1.231636
6  1.499002  2.776847 -0.228980 -0.261825

* Similarly with columns:

In [35]:
df1.iloc[:, [1, 3]]

           2         6
0  -0.767686 -0.399826
2  -0.085144 -1.231636
4   0.810422  1.314204
6   2.776847 -0.261825
8  -0.298624 -0.383581
10 -0.292211 -0.063091

* And both rows and columns:

In [36]:
df1.iloc[[1,3], [1,3]]

          2         6
2 -0.085144 -1.231636
6  2.776847 -0.261825

* Selecting via integer slicing selects the rows in the slice:

In [37]:
df1.iloc[2:4]

          0         2         4         6
4  0.451294  0.810422  0.846948  1.314204
6  1.499002  2.776847 -0.228980 -0.261825

* If we want the selection only on the columns, we just specify that we want all the rows:

In [38]:
df1.iloc[:, 1:3]

           2         4
0  -0.767686  0.054296
2  -0.085144 -0.147879
4   0.810422  0.846948
6   2.776847 -0.228980
8  -0.298624  0.206337
10 -0.292211 -1.844412

## Boolean Indexing

* Boolean indexing is used for filtering our data based on a particular condition.

* Conditions may be combined with boolean operators. In that case, *each condition must be put in parentheses*.

* The boolean operators are `~` (not), `&` (and), `|` (or).

* Setting the scene:

In [45]:
df1 = pd.DataFrame(np.random.randn(6,5), index=dates, columns=list('ABCDE'))
df1

                   A         B         C         D         E
2016-01-01 -0.259575 -0.716595  0.445886  1.968796  1.201251
2016-01-02 -0.610863  0.306992  0.143054 -0.560776  0.779249
2016-01-03  2.686894  1.004143  0.847663  0.796960 -1.171435
2016-01-04  0.967578 -0.356796  0.553169 -0.825141 -1.419492
2016-01-05  0.004924  0.150129 -0.069871 -0.520641 -0.535809
2016-01-06  0.278387  0.503030 -1.226951  0.893502 -1.704567

* Boolean AND

In [46]:
df1[(df1['A'] > 0) & (df1['A'] < 1)]

                   A         B         C         D         E
2016-01-04  0.967578 -0.356796  0.553169 -0.825141 -1.419492
2016-01-05  0.004924  0.150129 -0.069871 -0.520641 -0.535809
2016-01-06  0.278387  0.503030 -1.226951  0.893502 -1.704567

* Boolean OR:

In [47]:
df1[(df1['A'] > 2) | (df1['A'] < 0)]

                   A         B         C         D         E
2016-01-01 -0.259575 -0.716595  0.445886  1.968796  1.201251
2016-01-02 -0.610863  0.306992  0.143054 -0.560776  0.779249
2016-01-03  2.686894  1.004143  0.847663  0.796960 -1.171435

* Boolean NOT:

In [48]:
df1[~((df1['A'] > 2) | (df1['A'] < 0))]

                   A         B         C         D         E
2016-01-04  0.967578 -0.356796  0.553169 -0.825141 -1.419492
2016-01-05  0.004924  0.150129 -0.069871 -0.520641 -0.535809
2016-01-06  0.278387  0.503030 -1.226951  0.893502 -1.704567

## Selection by Callable

* We can also use a callable for indexing.

* One that receives one argument and returns a value that can be used for indexing.

* E.g., `True` or `False` for rows and a column selector for columns.

* Setting the scene:

In [49]:
df1 = pd.DataFrame(np.random.randn(6, 4),
                   index=list('abcdef'),
                   columns=list('ABCD'))
df1

          A         B         C         D
a  0.699162  0.277478  0.096886  0.999602
b -0.904538  2.019420 -0.330263  0.277574
c  0.137812  0.722670  1.362307  2.177825
d -0.202064 -1.291158 -1.328868  0.357604
e  1.478883  1.569192  0.071301 -0.421109
f  1.304271 -1.651930  0.286701  2.126461

* A callable on rows:

In [50]:
df1.loc[lambda df: df.A > 0, :]

          A         B         C         D
a  0.699162  0.277478  0.096886  0.999602
c  0.137812  0.722670  1.362307  2.177825
e  1.478883  1.569192  0.071301 -0.421109
f  1.304271 -1.651930  0.286701  2.126461

* A callable on rows and columns:

In [51]:
df1.loc[lambda df: df.A > 0, lambda df: ['C', 'D']]

          C         D
a  0.096886  0.999602
c  1.362307  2.177825
e  0.071301 -0.421109
f  0.286701  2.126461

* A callable on rows, by position:

In [52]:
df1.iloc[lambda df: [0, 1], :]

          A         B         C         D
a  0.699162  0.277478  0.096886  0.999602
b -0.904538  2.019420 -0.330263  0.277574

* A callable on rows and columns, by position:

In [53]:
df1.iloc[lambda df: [0, 1], lambda df: [2, 3]]

          C         D
a  0.096886  0.999602
b -0.330263  0.277574

## Multi-dimensional Indexing

* Pandas also supports multi-dimensional indexing, where an index is essentially a hierarchical structure.

* That means that we index first by the first dimension, then by the second, etc.

* As an example, we are going to use the [Airline On-Time Performance Data](https://www.transtats.bts.gov/Tables.asp?DB_ID=120&DB_Name=Airline%20On-Time%20Performance%20Data&DB_Short_Name=On-Time#), maintained by the [Bureau of Transportation Statistics (BTS)](https://www.bts.gov/) of the U.S. Department of Transportation.

* In particular, we'll use the Reporting Carrier On-Time Performance (1987-Present) dataset.

* It contains: "Monthly data reported by US certified air carriers that account for at least one percent of domestic scheduled passenger revenues--includes scheduled and actual arrival and departure times for flights".

* We'll use all the data for all the months of a single year. You can create this subset in [this online notebook](https://colab.research.google.com/drive/1GD_NAaLgIRQvAIDshATxJO_94MDpmYrV?usp=sharing)

* After processing and saving the file (e.g., `flights2020.csv.zip`), we can read it as follows:

In [70]:
flights = pd.read_csv('flights2020.csv.zip', index_col=0)
print(flights.shape)
flights.sample(5)

(18905, 109)

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
992831,2020,1,3,22,7,2020-03-22,OO,20304,OO,N260SY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1846591,2020,1,2,17,1,2020-02-17,WN,19393,WN,N498WN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556387,2020,1,3,3,2,2020-03-03,DL,19790,DL,N302DQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1355249,2020,1,2,11,2,2020-02-11,AA,19805,AA,N944AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250048,2020,1,1,13,1,2020-01-13,OO,20304,OO,N402SY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Sample
* Note that we used the `sample` method to get a subset of the `DataFrame`.

* The `sample` method can sample with or without replacement (parameter `replace`, default is `False`).

* We can also pass it a column of weights, indicating the probability that each row will get selected.

## Build a hierarchical index
* Now, let's create a hierarchical index using the following fields:
    * `CARRIER`
    * `ORIGIN`
    * `DEST`
    * `TAIL_NUM`
    * `FL_DATE`

In [71]:
selection = ['Reporting_Airline', 'Origin',  'Dest', 'Tail_Number', 'FlightDate']

hierarchical_flights = flights.set_index(selection)
hierarchical_flights = hierarchical_flights.sort_index(level=selection)
hierarchical_flights

                                                      Year  Quarter  Month  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11  2020        1      3
                              N292PQ      2020-02-17  2020        1      2
                              N324PQ      2020-02-26  2020        1      2
                  AEX    ATL  N8839E      2020-03-03  2020        1      3
                              N8969A      2020-01-22  2020        1      1
...                                                    ...      ...    ...
YX                TYS    LGA  N425YX      2020-03-02  2020        1      3
                              N433YX      2020-03-04  2020        1      3
                         MIA  N432YX      2020-03-01  2020        1      3
                  XNA    LGA  N120HQ      2020-01-09  2020        1      1
                              N420YX      2020-03-09  2020        1      3

                                                      DayofMonth  DayOfWeek  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11          11          3
                              N292PQ      2020-02-17          17          1
                              N324PQ      2020-02-26          26          3
                  AEX    ATL  N8839E      2020-03-03           3          2
                              N8969A      2020-01-22          22          3
...                                                          ...        ...
YX                TYS    LGA  N425YX      2020-03-02           2          1
                              N433YX      2020-03-04           4          3
                         MIA  N432YX      2020-03-01           1          7
                  XNA    LGA  N120HQ      2020-01-09           9          4
                              N420YX      2020-03-09           9          1

                                                      DOT_ID_Reporting_Airline  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11                     20363
                              N292PQ      2020-02-17                     20363
                              N324PQ      2020-02-26                     20363
                  AEX    ATL  N8839E      2020-03-03                     20363
                              N8969A      2020-01-22                     20363
...                                                                        ...
YX                TYS    LGA  N425YX      2020-03-02                     20452
                              N433YX      2020-03-04                     20452
                         MIA  N432YX      2020-03-01                     20452
                  XNA    LGA  N120HQ      2020-01-09                     20452
                              N420YX      2020-03-09                     20452

                                                     IATA_CODE_Reporting_Airline  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11                          9E
                              N292PQ      2020-02-17                          9E
                              N324PQ      2020-02-26                          9E
                  AEX    ATL  N8839E      2020-03-03                          9E
                              N8969A      2020-01-22                          9E
...                                                                          ...
YX                TYS    LGA  N425YX      2020-03-02                          YX
                              N433YX      2020-03-04                          YX
                         MIA  N432YX      2020-03-01                          YX
                  XNA    LGA  N120HQ      2020-01-09                          YX
                              N420YX      2020-03-09                          YX

                                                      Flight_Number_Reporting_Airline  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11                             5172
                              N292PQ      2020-02-17                             5197
                              N324PQ      2020-02-26                             5172
                  AEX    ATL  N8839E      2020-03-03                             5401
                              N8969A      2020-01-22                             5431
...                                                                               ...
YX                TYS    LGA  N425YX      2020-03-02                             4362
                              N433YX      2020-03-04                             4361
                         MIA  N432YX      2020-03-01                             4582
                  XNA    LGA  N120HQ      2020-01-09                             4506
                              N420YX      2020-03-09                             4363

                                                      OriginAirportID  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11            10135
                              N292PQ      2020-02-17            10135
                              N324PQ      2020-02-26            10135
                  AEX    ATL  N8839E      2020-03-03            10185
                              N8969A      2020-01-22            10185
...                                                               ...
YX                TYS    LGA  N425YX      2020-03-02            15412
                              N433YX      2020-03-04            15412
                         MIA  N432YX      2020-03-01            15412
                  XNA    LGA  N120HQ      2020-01-09            15919
                              N420YX      2020-03-09            15919

                                                      OriginAirportSeqID  ...  \
Reporting_Airline Origin Dest Tail_Number FlightDate                      ...
9E                ABE    ATL  N176PQ      2020-03-11             1013506  ...
                              N292PQ      2020-02-17             1013506  ...
                              N324PQ      2020-02-26             1013506  ...
                  AEX    ATL  N8839E      2020-03-03             1018502  ...
                              N8969A      2020-01-22             1018502  ...
...                                                                  ...  ...
YX                TYS    LGA  N425YX      2020-03-02             1541205  ...
                              N433YX      2020-03-04             1541205  ...
                         MIA  N432YX      2020-03-01             1541205  ...
                  XNA    LGA  N120HQ      2020-01-09             1591904  ...
                              N420YX      2020-03-09             1591904  ...

                                                      Div4WheelsOff  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11            NaN
                              N292PQ      2020-02-17            NaN
                              N324PQ      2020-02-26            NaN
                  AEX    ATL  N8839E      2020-03-03            NaN
                              N8969A      2020-01-22            NaN
...                                                             ...
YX                TYS    LGA  N425YX      2020-03-02            NaN
                              N433YX      2020-03-04            NaN
                         MIA  N432YX      2020-03-01            NaN
                  XNA    LGA  N120HQ      2020-01-09            NaN
                              N420YX      2020-03-09            NaN

                                                     Div4TailNum Div5Airport  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11         NaN         NaN
                              N292PQ      2020-02-17         NaN         NaN
                              N324PQ      2020-02-26         NaN         NaN
                  AEX    ATL  N8839E      2020-03-03         NaN         NaN
                              N8969A      2020-01-22         NaN         NaN
...                                                          ...         ...
YX                TYS    LGA  N425YX      2020-03-02         NaN         NaN
                              N433YX      2020-03-04         NaN         NaN
                         MIA  N432YX      2020-03-01         NaN         NaN
                  XNA    LGA  N120HQ      2020-01-09         NaN         NaN
                              N420YX      2020-03-09         NaN         NaN

                                                      Div5AirportID  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11            NaN
                              N292PQ      2020-02-17            NaN
                              N324PQ      2020-02-26            NaN
                  AEX    ATL  N8839E      2020-03-03            NaN
                              N8969A      2020-01-22            NaN
...                                                             ...
YX                TYS    LGA  N425YX      2020-03-02            NaN
                              N433YX      2020-03-04            NaN
                         MIA  N432YX      2020-03-01            NaN
                  XNA    LGA  N120HQ      2020-01-09            NaN
                              N420YX      2020-03-09            NaN

                                                     Div5AirportSeqID  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11              NaN
                              N292PQ      2020-02-17              NaN
                              N324PQ      2020-02-26              NaN
                  AEX    ATL  N8839E      2020-03-03              NaN
                              N8969A      2020-01-22              NaN
...                                                               ...
YX                TYS    LGA  N425YX      2020-03-02              NaN
                              N433YX      2020-03-04              NaN
                         MIA  N432YX      2020-03-01              NaN
                  XNA    LGA  N120HQ      2020-01-09              NaN
                              N420YX      2020-03-09              NaN

                                                      Div5WheelsOn  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11           NaN
                              N292PQ      2020-02-17           NaN
                              N324PQ      2020-02-26           NaN
                  AEX    ATL  N8839E      2020-03-03           NaN
                              N8969A      2020-01-22           NaN
...                                                            ...
YX                TYS    LGA  N425YX      2020-03-02           NaN
                              N433YX      2020-03-04           NaN
                         MIA  N432YX      2020-03-01           NaN
                  XNA    LGA  N120HQ      2020-01-09           NaN
                              N420YX      2020-03-09           NaN

                                                      Div5TotalGTime  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11             NaN
                              N292PQ      2020-02-17             NaN
                              N324PQ      2020-02-26             NaN
                  AEX    ATL  N8839E      2020-03-03             NaN
                              N8969A      2020-01-22             NaN
...                                                              ...
YX                TYS    LGA  N425YX      2020-03-02             NaN
                              N433YX      2020-03-04             NaN
                         MIA  N432YX      2020-03-01             NaN
                  XNA    LGA  N120HQ      2020-01-09             NaN
                              N420YX      2020-03-09             NaN

                                                      Div5LongestGTime  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11               NaN
                              N292PQ      2020-02-17               NaN
                              N324PQ      2020-02-26               NaN
                  AEX    ATL  N8839E      2020-03-03               NaN
                              N8969A      2020-01-22               NaN
...                                                                ...
YX                TYS    LGA  N425YX      2020-03-02               NaN
                              N433YX      2020-03-04               NaN
                         MIA  N432YX      2020-03-01               NaN
                  XNA    LGA  N120HQ      2020-01-09               NaN
                              N420YX      2020-03-09               NaN

                                                      Div5WheelsOff  \
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11            NaN
                              N292PQ      2020-02-17            NaN
                              N324PQ      2020-02-26            NaN
                  AEX    ATL  N8839E      2020-03-03            NaN
                              N8969A      2020-01-22            NaN
...                                                             ...
YX                TYS    LGA  N425YX      2020-03-02            NaN
                              N433YX      2020-03-04            NaN
                         MIA  N432YX      2020-03-01            NaN
                  XNA    LGA  N120HQ      2020-01-09            NaN
                              N420YX      2020-03-09            NaN

                                                     Div5TailNum
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ABE    ATL  N176PQ      2020-03-11         NaN
                              N292PQ      2020-02-17         NaN
                              N324PQ      2020-02-26         NaN
                  AEX    ATL  N8839E      2020-03-03         NaN
                              N8969A      2020-01-22         NaN
...                                                          ...
YX                TYS    LGA  N425YX      2020-03-02         NaN
                              N433YX      2020-03-04         NaN
                         MIA  N432YX      2020-03-01         NaN
                  XNA    LGA  N120HQ      2020-01-09         NaN
                              N420YX      2020-03-09         NaN

[18905 rows x 104 columns]

## MultiIndex
* A hierarchical index is of type `MultiIndex`. 

* The levels of a `MultiIndex` are the names of the columns we used for indexing.

* The labels are the values in a level, that is, the values of the respective column.

* We can refer to levels by name or position. Level 0 is the outermost level.

* We'll select the columns DepTime and DepDelay where the carrier was American Airlines, Delta, or United Airways.

In [83]:
hierarchical_flights.loc[['AA', 'DL', 'UA'], ['DepTime', 'DepDelay']]

                                                      DepTime  DepDelay
Reporting_Airline Origin Dest Tail_Number FlightDate
AA                ABQ    DFW  N775XF      2020-03-16   1442.0      -7.0
                              N914AN      2020-02-25    757.0      -7.0
                              N944NN      2020-03-25      NaN       NaN
                              N946AN      2020-02-16    607.0      -2.0
                              N971AN      2020-02-29    759.0      -5.0
...                                                       ...       ...
UA                TPA    SFO  N66831      2020-03-23   1927.0      46.0
                  TUL    DEN  N878UA      2020-01-19    720.0     -10.0
                         IAH  N23707      2020-02-28    651.0      -9.0
                  TUS    IAH  NaN         2020-03-28      NaN       NaN
                         ORD  N439UA      2020-03-24   1138.0      -4.0

[6388 rows x 2 columns]

* Now, let's put the hierarchical index into work.

* We'll select the rows whose carrier was American Airlines, Delta, or United Airlines and the origin was Chicago O'Hare (ORD) or Des Moines International Airport (DSM). 

* We'll wrap the two levels of the index in a tuple to do the job.

In [84]:
hierarchical_flights.loc[(['AA', 'DL', 'UA'], ['ORD', 'DSM']), ['DepTime', 'DepDelay']]

                                                      DepTime  DepDelay
Reporting_Airline Origin Dest Tail_Number FlightDate
AA                ORD    ATL  N8009T      2020-02-08   1939.0      39.0
                              N907NN      2020-02-02    919.0      41.0
                              N916NN      2020-01-12      NaN       NaN
                         AUS  N358PW      2020-01-16   1506.0       1.0
                         BDL  N828AW      2020-02-19   1513.0      -2.0
...                                                       ...       ...
UA                DSM    DEN  N805UA      2020-02-21   1647.0      -8.0
                         IAH  N66828      2020-03-11    555.0     -15.0
                              N855UA      2020-03-16    603.0      -2.0
                         ORD  N27239      2020-01-25    703.0      63.0
                              N426UA      2020-02-22    509.0      -6.0

[366 rows x 2 columns]

## IndexSlice
* Suppose now that we want all flights between these two airports (origin DSM or ORD), and not just from these two carriers.

* We can do that by using an `IndexSlice`.

In [85]:
hierarchical_flights.loc[pd.IndexSlice[:, ['ORD', 'DSM']], 
                         ['DepTime', 'DepDelay']]

                                                      DepTime  DepDelay
Reporting_Airline Origin Dest Tail_Number FlightDate
9E                ORD    CVG  N8839E      2020-01-07   1225.0     -10.0
                              N8891A      2020-02-12      NaN       NaN
                              N8908D      2020-03-25      NaN       NaN
                              N8969A      2020-03-22   2102.0      67.0
                         JFK  N926XJ      2020-03-13   1905.0      45.0
...                                                       ...       ...
UA                DSM    IAH  N855UA      2020-03-16    603.0      -2.0
                         ORD  N27239      2020-01-25    703.0      63.0
                              N426UA      2020-02-22    509.0      -6.0
WN                DSM    DEN  N8316H      2020-03-30   1648.0      -7.0
YX                DSM    PHL  N417YX      2020-02-07    601.0       1.0

[835 rows x 2 columns]

## Using more information from the index
* We can get even more creative.

* Remember that the last level of the index was the flight date.

* Suppose we want to find the flights in the first half of January from Chicago O'Hare (ORD) to Des Moines International Airport (DSM). We'll do:

In [93]:
hierarchical_flights.loc[pd.IndexSlice[:, 'ORD', 'DSM', :, '2020-01-01':'2020-01-15'],
                         ['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']]

,,,,,DepTime,DepDelay,ArrTime,ArrDelay
Reporting_Airline,Origin,Dest,Tail_Number,FlightDate,,,,
MQ,ORD,DSM,N922AE,2020-01-14,1712.0,-3.0,1830.0,-11.0
OO,ORD,DSM,N742SK,2020-01-14,1400.0,-5.0,1519.0,-17.0
UA,ORD,DSM,N17245,2020-01-15,2122.0,-3.0,2251.0,-1.0

# Pivot

* The pivot operation creates new columns out of the values of a single column.

* Let's start setting the scene:

In [94]:
import pandas as pd
import numpy as np

dates_range = pd.date_range('2016/10/1', periods=3).repeat(4)
dates_range

DatetimeIndex(['2016-10-01', '2016-10-01', '2016-10-01', '2016-10-01',
               '2016-10-02', '2016-10-02', '2016-10-02', '2016-10-02',
               '2016-10-03', '2016-10-03', '2016-10-03', '2016-10-03'],
              dtype='datetime64[ns]', freq=None)

In [95]:
statuses = np.tile(list('ABCD'), 3)
statuses

array(['A', 'B', 'C', 'D', 'A', 'B', 'C', 'D', 'A', 'B', 'C', 'D'],
      dtype='<U1')

In [96]:
values = np.random.randn(12)
values

array([-1.60030834, -0.82416804,  1.38646703, -0.23583651, -1.52077443,
       -0.90071662,  0.17390069,  2.10097213, -1.74931579,  0.01652192,
        0.75732019, -1.07581753])

In [97]:
df = pd.DataFrame({'date': dates_range, 'status': statuses, 'value': values})
df.head(3)

        date status     value
0 2016-10-01      A -1.600308
1 2016-10-01      B -0.824168
2 2016-10-01      C  1.386467

* Now, if we want to operate on the variables, for example on the `status`, a better representation would be to turn the statuses to distinct columns.

* We can do that with the `pivot` method. It takes the following arguments:
    * `index`: The column that will become the new index.
    * `columns`: The column whose values will become the new columns.
    * `values`: The column whose values will fill the new dataframe.

In [98]:
df.pivot(index='date', columns='status', values='value')

status             A         B         C         D
date
2016-10-01 -1.600308 -0.824168  1.386467 -0.235837
2016-10-02 -1.520774 -0.900717  0.173901  2.100972
2016-10-03 -1.749316  0.016522  0.757320 -1.075818

## Pivot Tables

* We can also pivot a table, yielding a dataframe with many dimensions.

* This can be created with the `pivot_table` function. It takes the following arguments:

    * `data`: A DataFrame object
    * `values`: A column or a list of columns to aggregate.
    * `index`: A column, or array, which has the same length as data, or list of them. Will be used as the index of the pivot table. 
    * `columns`: A column, or array which has the same length as data, or list of them. The values will be used to create the columns of the pivot table.
    * `aggfunc`: The function to use for aggregation, defaulting to `numpy.mean`.

In [99]:
import datetime

df = pd.DataFrame({'A': ['one', 'one', 'two', 'three'] * 6,
                   'B': ['A', 'B', 'C'] * 8,
                   'C': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 4,
                   'D': np.random.randn(24),
                   'E': np.random.randn(24),
                   'F': [datetime.datetime(2016, i, 1) for i in range(1, 13)] +
                        [datetime.datetime(2016, i, 15) for i in range(1, 13)]})
df.head(10)

       A  B    C         D         E          F
0    one  A  foo -0.830445 -2.167503 2016-01-01
1    one  B  foo -0.087809 -0.187476 2016-02-01
2    two  C  foo  0.543803  1.200540 2016-03-01
3  three  A  bar -0.755718  1.263665 2016-04-01
4    one  B  bar  2.597523 -0.115049 2016-05-01
5    one  C  bar -0.808059 -0.729059 2016-06-01
6    two  A  foo  2.057551 -0.918923 2016-07-01
7  three  B  foo -0.576353  0.128176 2016-08-01
8    one  C  foo  0.280465  0.469245 2016-09-01
9    one  A  bar  1.056617  1.719957 2016-10-01

In [100]:
# Aggregating on D, indexing on A and B, using as cols the values of C 
pv = pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])
pv

C             bar       foo
A     B
one   A  0.671850 -0.564271
      B  0.279253 -0.503705
      C -0.464951  0.605391
three A  0.317410       NaN
      B       NaN -0.818325
      C -0.145921       NaN
two   A       NaN  0.773937
      B -0.078196       NaN
      C       NaN  0.579692

* Note that this is a *hierarchical index*, comprising both columns A and B.

* You can think of each value of the hierarchical index as a tuple.

In [101]:
pv.index

MultiIndex([(  'one', 'A'),
            (  'one', 'B'),
            (  'one', 'C'),
            ('three', 'A'),
            ('three', 'B'),
            ('three', 'C'),
            (  'two', 'A'),
            (  'two', 'B'),
            (  'two', 'C')],
           names=['A', 'B'])

* But of course it is not necessary to have a hierarchical index as a result of a `pivot_table`.

In [102]:
pv = pd.pivot_table(df, values='D', index=['B'], 
                    columns=['A', 'C'], aggfunc=np.sum)
pv

A       one               three                 two
C       bar       foo       bar       foo       bar       foo
B
A  1.343700 -1.128542  0.634820       NaN       NaN  1.547874
B  0.558505 -1.007411       NaN -1.636651 -0.156392       NaN
C -0.929901  1.210782 -0.291843       NaN       NaN  1.159383

In [103]:
pv.index

Index(['A', 'B', 'C'], dtype='object', name='B')

* And you can add multiple aggregation functions (by default, the mean is computed).

In [104]:
pv = pd.pivot_table(df, values='D', index=['B'], 
                    columns=['A', 'C'], aggfunc={"D":[min, max]})
pv

        max                                                         min  \
A       one               three                 two                 one
C       bar       foo       bar       foo       bar       foo       bar
B
A  1.056617 -0.298097  1.390538       NaN       NaN  2.057551  0.287084
B  2.597523 -0.087809       NaN -0.576353  0.037621       NaN -2.039018
C -0.121843  0.930317 -0.036965       NaN       NaN  0.615581 -0.808059


A               three                 two
C       foo       bar       foo       bar       foo
B
A -0.830445 -0.755718       NaN       NaN -0.509677
B -0.919602       NaN -1.060298 -0.194014       NaN
C  0.280465 -0.254878       NaN       NaN  0.543803

# Stacking and Unstacking

* A related operation to pivoting is *stacking*, and its inverse, *unstacking*.

* The stack operation takes `DataFrame` columns and adds them to the (hierarchical) index as another component.

* The unstack operation takes a component from the hierarchical index and turns it to a column.

### Create a List of Tuples

* We'll start by creating a multi-level index.

* The index will be constructed by two-elements tuples, using Python's `zip()` function.

* `zip` takes as arguments iterables and aggregates (zipping) the elements from each one.

* If `a` and `b` are lists, `zip(a, b)` will produce the tuples `(a[0], b[0]), (a[1], b[1]), ...` until `a` or `b` are exhausted.

In [144]:
tuples = list(zip(['bar', 'bar', 'baz', 'baz','foo', 'foo', 'qux', 'qux'],
                  ['one', 'two', 'one', 'two','one', 'two', 'one', 'two']))

tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

* We will create our `multi-index` from these tuples.

In [147]:
multi_index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])
multi_index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

* And now we can setup a hierarchical view of the dataframe using this multi-indexing.

In [148]:
import pandas as pd
df = pd.DataFrame(np.random.randn(8, 2), index=multi_index, columns=['A', 'B'])
df

                     A         B
first second
bar   one    -0.178685  0.267407
      two     0.774693 -1.290301
baz   one     0.305362  1.577292
      two    -0.855979  1.013811
foo   one    -0.023160 -0.180397
      two    -0.439292 -0.443660
qux   one    -1.377382 -0.577373
      two    -0.704596 -1.360422

* By calling `stack()`, now, we can add a third level to our multi-index, which will correspond to the columns `A` and `B`.

In [149]:
stacked = df.stack()
stacked

first  second
bar    one     A   -0.178685
               B    0.267407
       two     A    0.774693
               B   -1.290301
baz    one     A    0.305362
               B    1.577292
       two     A   -0.855979
               B    1.013811
foo    one     A   -0.023160
               B   -0.180397
       two     A   -0.439292
               B   -0.443660
qux    one     A   -1.377382
               B   -0.577373
       two     A   -0.704596
               B   -1.360422
dtype: float64

In [109]:
stacked.index

MultiIndex([('bar', 'one', 'A'),
            ('bar', 'one', 'B'),
            ('bar', 'two', 'A'),
            ('bar', 'two', 'B'),
            ('baz', 'one', 'A'),
            ('baz', 'one', 'B'),
            ('baz', 'two', 'A'),
            ('baz', 'two', 'B'),
            ('foo', 'one', 'A'),
            ('foo', 'one', 'B'),
            ('foo', 'two', 'A'),
            ('foo', 'two', 'B'),
            ('qux', 'one', 'A'),
            ('qux', 'one', 'B'),
            ('qux', 'two', 'A'),
            ('qux', 'two', 'B')],
           names=['first', 'second', None])

* The inverse operation is `unstack()`.

In [153]:
unstacked = stacked.unstack()
unstacked

                     A         B
first second
bar   one    -0.178685  0.267407
      two     0.774693 -1.290301
baz   one     0.305362  1.577292
      two    -0.855979  1.013811
foo   one    -0.023160 -0.180397
      two    -0.439292 -0.443660
qux   one    -1.377382 -0.577373
      two    -0.704596 -1.360422

In [154]:
unstacked.index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

* Note that `unstack()` by default unstacks the last level, but we can choose differently if we want.

* The following is the same as the `stacked.unstack()` that we did before:

In [155]:
unstacked = stacked.unstack(2)
unstacked

                     A         B
first second
bar   one    -0.178685  0.267407
      two     0.774693 -1.290301
baz   one     0.305362  1.577292
      two    -0.855979  1.013811
foo   one    -0.023160 -0.180397
      two    -0.439292 -0.443660
qux   one    -1.377382 -0.577373
      two    -0.704596 -1.360422

In [113]:
unstacked.index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

* But here we unstack a different column:

In [156]:
unstacked = stacked.unstack(1)
unstacked

second        one       two
first
bar   A -0.178685  0.774693
      B  0.267407 -1.290301
baz   A  0.305362 -0.855979
      B  1.577292  1.013811
foo   A -0.023160 -0.439292
      B -0.180397 -0.443660
qux   A -1.377382 -0.704596
      B -0.577373 -1.360422

In [115]:
unstacked.index

MultiIndex([('bar', 'A'),
            ('bar', 'B'),
            ('baz', 'A'),
            ('baz', 'B'),
            ('foo', 'A'),
            ('foo', 'B'),
            ('qux', 'A'),
            ('qux', 'B')],
           names=['first', None])

* And here we unstack the first column:

In [116]:
unstacked = stacked.unstack(0)
unstacked

first          bar       baz       foo       qux
second
one    A  0.877354 -0.472287 -1.271971 -0.403733
       B  1.651955  2.038974 -0.150017 -0.484515
two    A -0.651503  0.090599 -0.478620  0.463032
       B  0.028268  1.259275  2.533842 -0.496064

In [117]:
unstacked.index

MultiIndex([('one', 'A'),
            ('one', 'B'),
            ('two', 'A'),
            ('two', 'B')],
           names=['second', None])

* A more advanced use of `stack` is when the columns also have a `MultiIndex`.

In [166]:
columns = pd.MultiIndex.from_tuples([
        ('A', 'cat', 'long'), ('B', 'cat', 'long'),
        ('A', 'dog', 'short'), ('B', 'dog', 'short')],
        names=['exp', 'animal', 'hair_length'])

df = pd.DataFrame(np.random.randn(4, 4), columns=columns)
df

exp                 A         B         A         B
animal            cat       cat       dog       dog
hair_length      long      long     short     short
0            0.382368  1.636260  1.263976  1.368695
1            0.317200  1.477210 -0.111311  0.165878
2           -0.986651 -0.538316 -0.674443  1.166628
3           -1.699728  0.088001  0.112492 -0.447981

* By stacking, we move `hair_length` into the index, creating a MultiIndex with two indices.

In [170]:
df.stack()

exp                   A                   B
animal              cat       dog       cat       dog
  hair_length
0 long         0.382368       NaN  1.636260       NaN
  short             NaN  1.263976       NaN  1.368695
1 long         0.317200       NaN  1.477210       NaN
  short             NaN -0.111311       NaN  0.165878
2 long        -0.986651       NaN -0.538316       NaN
  short             NaN -0.674443       NaN  1.166628
3 long        -1.699728       NaN  0.088001       NaN
  short             NaN  0.112492       NaN -0.447981

* We can also select the levels of the column `MultiIndex` to stack based on their level names:

In [119]:
df.stack(level=['animal', 'hair_length'])

exp                          A         B
  animal hair_length
0 cat    long         1.044230 -0.301129
  dog    short        0.043074 -0.190875
1 cat    long        -0.280302 -0.771359
  dog    short        1.412656 -0.310731
2 cat    long        -1.222375  1.114833
  dog    short        0.845889 -0.618473
3 cat    long        -0.724704 -0.810040
  dog    short       -0.856889  0.286642

* Or based on their level numbers:

In [120]:
df.stack(level=[1, 2])

exp                          A         B
  animal hair_length
0 cat    long         1.044230 -0.301129
  dog    short        0.043074 -0.190875
1 cat    long        -0.280302 -0.771359
  dog    short        1.412656 -0.310731
2 cat    long        -1.222375  1.114833
  dog    short        0.845889 -0.618473
3 cat    long        -0.724704 -0.810040
  dog    short       -0.856889  0.286642

# Homework
Using the Airline On-Time Performance dataset, study the flights in 2018 and find the carrier with the more delayed flights from Chicago O'Hare.